spring:
  datasource:
    url: "jdbc:postgresql://localhost:6540/warehouse"
    username: warehouse
    password: warehouse
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: create
      dialect: "org.hibernate.dialect.PostgreSQLDialect"
    show-sql: false
  sql:
    init:
      mode: always