warehouse:
  spring:
    datasource:
      url: "jdbc:postgresql://localhost:6541/analyzer"
      username: analyzer
      password: analyzer
      driver-class-name: "org.postgresql.Driver"
    jpa:
      hibernate:
        ddl-auto: create-drop
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
      show-sql: false