grpc:
  server:
    port: 59091

collector:
  spring:
    kafka:
      bootstrap-server: "localhost:9092"
      producer:
        key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
        value-serializer: "serialization.avro.AvroSerializer"
      topics:
        hub-topic-name: "telemetry.hubs.v1"
        sensor-topic-name: "telemetry.sensors.v1"
        snapshots-topic-name: "telemetry.snapshots.v1"