analyzer:
  grpc:
    client:
      hub-router:
        address: "static://localhost:59090"
        enableKeepAlive: true
        keepAliveWithoutCalls: true
        negotiationType: plaintext

spring:
  datasource:
    url: "jdbc:postgresql://localhost:6541/analyzer"
    username: analyzer
    password: analyzer
    driver-class-name: "org.postgresql.Driver"

  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: "org.hibernate.dialect.PostgreSQLDialect"
    show-sql: false

  kafka:
    bootstrap-server: "localhost:9092"
    consumer:
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      snapshot-value-deserializer: "deserialization.avro.SnapshotDeserializer"
      snapshot-group-id: analyzer-snapshot-group
      hub-event-value-deserializer: "deserialization.avro.HubEventDeserializer"
      hub-event-group-id: analyzer-hub-group
    topics:
      hub-topic-name: "telemetry.hubs.v1"
      snapshots-topic-name: "telemetry.snapshots.v1"