spring:
  datasource:
    url: "jdbc:postgresql://store-db:5432/store"
    username: store
    password: store
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: create
      dialect: "org.hibernate.dialect.PostgreSQLDialect"
    show-sql: false
  sql:
    init:
      mode: always